services:
  postgres:
    image: postgres:15-alpine
    container_name: drackymapp_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: drackymapp
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - payment-network
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  payment-network:
    driver: bridge

volumes:
  pgdata:
